const $=id=>document.getElementById(id);
const SESSION_KEY='taxiYaSession';
const api=(path,opts={})=>fetch('/api'+path,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.detail||'Ha ocurrido un error');return d});
function result(id,msg,error=false){const e=$(id);e.className='result';if(error)e.classList.add('error');e.innerHTML=msg}
function hideAll(){document.querySelectorAll('#auth .onboarding,#rolePicker,.role-view').forEach(e=>e.classList.add('hidden'))}
function saveSession(s){localStorage.setItem(SESSION_KEY,JSON.stringify(s))}
function getSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
function showAuth(){localStorage.removeItem(SESSION_KEY);watchers.forEach(w=>navigator.geolocation.clearWatch(w));watchers.length=0;clearInterval(taxiRefreshTimer);clearInterval(driverRideTimer);hideAll();$('auth').classList.remove('hidden');$('rolePicker').classList.remove('hidden')}
function showOnboarding(id){hideAll();$('auth').classList.remove('hidden');$(id).classList.remove('hidden')}
function openCustomer(s){hideAll();$('auth').classList.add('hidden');$('customerApp').classList.remove('hidden');$('customerWelcome').textContent=` · ${s.name}`;$('customerNameHidden')?.remove();ensureCustomerMap();startTaxiMapRefresh(customerMap)}
function openDriver(s){hideAll();$('auth').classList.add('hidden');$('driverApp').classList.remove('hidden');$('driverWelcome').textContent=` · ${s.name}`;$('availabilityToggle').classList.toggle('on',!!s.available);$('availabilityToggle').innerHTML=s.available?'<i></i> Estado: Libre':'<i></i> Estado: Ocupado';ensureDriverMap();loadStops();loadDriverRides();clearInterval(driverRideTimer);driverRideTimer=setInterval(loadDriverRides,5000);startTaxiMapRefresh(driverMap)}
function openAdmin(){hideAll();$('auth').classList.add('hidden');$('adminApp').classList.remove('hidden');ensureAdminMap();loadAdminDashboard()}

document.querySelectorAll('[data-logout]').forEach(b=>b.onclick=showAuth);
$('chooseCustomer').onclick=()=>showOnboarding('customerOnboarding');
$('chooseDriver').onclick=()=>showOnboarding('driverOnboarding');
$('chooseAdmin').onclick=()=>showOnboarding('adminOnboarding');
$('customerEnter').onclick=()=>{const name=$('customerSignupName').value.trim(),phone=$('customerSignupPhone').value.trim();if(!name||!phone)return result('rideResult','Indica nombre y teléfono.',true);saveSession({role:'customer',name,phone});openCustomer({role:'customer',name,phone})};
$('adminEnter').onclick=()=>{if($('adminCode').value!=='123456'){result('adminLoginResult','Clave incorrecta.',true);return}saveSession({role:'admin'});openAdmin()};
$('register').onclick=async()=>{try{const d=await api('/drivers/register',{method:'POST',body:JSON.stringify({name:$('driverName').value,phone:$('driverPhone').value,license:$('license').value,plate:$('plate').value})});$('driverId').value=d.driver_id;$('driverActivation').classList.remove('hidden');result('driverResult','Registro creado. Ahora activa tu perfil con la clave.')}catch(e){result('driverResult',e.message,true)}};
$('activate').onclick=async()=>{try{const d=await api('/drivers/activate',{method:'POST',body:JSON.stringify({driver_id:$('driverId').value,code:$('code').value,device_id:'web-demo-'+Date.now()})});const s={role:'driver',driverId:$('driverId').value,name:$('driverName').value,phone:$('driverPhone').value,status:d.status,available:false};saveSession(s);openDriver(s)}catch(e){result('driverResult',e.message,true)}};

const alcantarilla=[37.969,-1.217];const maps=[];let customerOriginCoords=null,customerDestinationCoords=null;const markers={};const taxiMapMarkers={};const previousCoords={};let customerMap,driverMap,adminMap;const watchers=[];let taxiRefreshTimer,driverRideTimer;
function taxiColor(t){return t.available&&!t.busy?'#58c96b':'#df4f4f'}
async function refreshTaxiMap(map){try{const locations=await api('/locations');locations.filter(x=>x.role==='driver').forEach(t=>{const color=taxiColor(t),icon=taxiIcon(0,color);if(taxiMapMarkers[t.entity_id]){taxiMapMarkers[t.entity_id].setLatLng([t.lat,t.lng]).setIcon(icon)}else taxiMapMarkers[t.entity_id]=L.marker([t.lat,t.lng],{icon,zIndexOffset:500}).addTo(map);});}catch{}}
function startTaxiMapRefresh(map){refreshTaxiMap(map);clearInterval(taxiRefreshTimer);taxiRefreshTimer=setInterval(()=>refreshTaxiMap(map),5000)}
function bearing(a,b){const r=Math.PI/180,y=Math.sin((b[1]-a[1])*r)*Math.cos(b[0]*r),x=Math.cos(a[0]*r)*Math.sin(b[0]*r)-Math.sin(a[0]*r)*Math.cos(b[0]*r)*Math.cos((b[1]-a[1])*r);return (Math.atan2(y,x)*180/Math.PI+360)%360}
function taxiIcon(angle=0,color='#f4c51b'){return L.divIcon({className:'taxi-div-icon',iconSize:[32,38],iconAnchor:[16,19],html:`<div class="taxi-marker" style="transform:rotate(${Math.round(angle)}deg)" aria-label="Taxi"><svg viewBox="0 0 32 48" aria-hidden="true"><rect x="7" y="8" width="18" height="33" rx="7" fill="${color}" stroke="#17181d" stroke-width="2"/><rect x="10" y="13" width="12" height="9" rx="2" fill="#26313a"/><rect x="10" y="25" width="12" height="5" rx="2" fill="#f8df55"/><rect x="11" y="3" width="10" height="5" rx="2" fill="${color}" stroke="#17181d" stroke-width="1.5"/><circle cx="7" cy="18" r="2" fill="#17181d"/><circle cx="25" cy="18" r="2" fill="#17181d"/><circle cx="7" cy="35" r="2" fill="#17181d"/><circle cx="25" cy="35" r="2" fill="#17181d"/></svg></div>`})}
function makeMap(id){const map=L.map(id,{preferCanvas:true}).setView(alcantarilla,14);const primary=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'© Esri, © OpenStreetMap'});let tileErrors=0,fallbackLoaded=false;primary.on('tileerror',()=>{if(++tileErrors>=2&&!fallbackLoaded){fallbackLoaded=true;map.removeLayer(primary);L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{maxZoom:20,attribution:'© CARTO, © OpenStreetMap'}).addTo(map)}}).addTo(map);L.marker(alcantarilla).addTo(map).bindPopup('Alcantarilla · Taxi Ya');maps.push(map);map.whenReady(()=>{map.invalidateSize();setTimeout(()=>map.invalidateSize(),500)});return map}
function ensureCustomerMap(){if(!customerMap){customerMap=makeMap('customerMap');customerMap.on('click',e=>{customerOriginCoords={lat:e.latlng.lat,lng:e.latlng.lng};$('origin').value='Recogida fijada en el mapa';$('customerGpsStatus').textContent='Recogida fijada automáticamente en el mapa'})}setTimeout(()=>customerMap.invalidateSize(),100)}
function ensureDriverMap(){if(!driverMap)driverMap=makeMap('driverMap');setTimeout(()=>driverMap.invalidateSize(),100)}
let adminMarker;
function ensureAdminMap(){if(!adminMap){adminMap=makeMap('adminMap');adminMap.on('click',e=>{const lat=e.latlng.lat.toFixed(6),lng=e.latlng.lng.toFixed(6);$('stopLat').value=lat;$('stopLng').value=lng;if(adminMarker)adminMarker.setLatLng(e.latlng);else adminMarker=L.marker(e.latlng).addTo(adminMap).bindPopup('Nueva parada').openPopup()})}setTimeout(()=>adminMap.invalidateSize(),100)}
setTimeout(()=>maps.forEach(m=>m.invalidateSize()),1200);window.addEventListener('resize',()=>maps.forEach(m=>m.invalidateSize()));
function startGps(map,role,idProvider,statusId,rideProvider){if(!navigator.geolocation){$(statusId).textContent='GPS no disponible';return}$(statusId).textContent='Solicitando permiso…';const w=navigator.geolocation.watchPosition(async pos=>{const lat=pos.coords.latitude,lng=pos.coords.longitude;if(role==='customer'){customerOriginCoords={lat,lng};$('origin').value='Mi ubicación actual'}map.setView([lat,lng],16);const previous=previousCoords[role],angle=Number.isFinite(pos.coords.heading)&&pos.coords.heading>=0?pos.coords.heading:(previous?bearing(previous,[lat,lng]):0);previousCoords[role]=[lat,lng];if(role==='driver'){if(markers[role]){markers[role].setLatLng([lat,lng]);const el=markers[role].getElement()?.querySelector('.taxi-marker');if(el)el.style.transform=`rotate(${Math.round(angle)}deg)`}else markers[role]=L.marker([lat,lng],{icon:taxiIcon(angle),zIndexOffset:1000}).addTo(map).bindPopup('Taxi Ya · ubicación en tiempo real')}else if(markers[role])markers[role].setLatLng([lat,lng]);else markers[role]=L.marker([lat,lng]).addTo(map).bindPopup('Tu ubicación');$(statusId).textContent='Ubicación compartida';try{const sync=await api('/locations',{method:'POST',body:JSON.stringify({entity_id:idProvider(),role,lat,lng,ride_id:rideProvider?rideProvider():null,available:role==='driver'?Boolean(getSession()?.available):null})});if(role==='driver'&&sync.auto_queue){showQueueCard(sync.auto_queue.stop_id,sync.auto_queue.position);$(statusId).textContent=`En cola unificada · posición ${sync.auto_queue.position}`}else if(role==='driver'&&sync.queue){showQueueCard(sync.queue.stop_id,sync.queue.position);$(statusId).textContent=`En cola unificada · posición ${sync.queue.position}`}else if(role==='driver'&&sync.exited_stop_ids?.length){$('driverQueueCard')?.classList.add('hidden');$(statusId).textContent='Fuera de la parada · cola liberada'}}catch(e){$(statusId).textContent='GPS activo · sincronización pendiente'}},()=>$(statusId).textContent='Permiso de ubicación no concedido',{enableHighAccuracy:true,maximumAge:10000,timeout:15000});watchers.push(w)}
$('customerGps').onclick=()=>{const s=getSession();startGps(customerMap,'customer',()=>s.phone,'customerGpsStatus',()=>$('rideResult')?.dataset.id||null)};
$('driverGps').onclick=()=>{if(driverWatching)return;const s=getSession();driverWatching=true;startGps(driverMap,'driver',()=>s.driverId,'driverGpsStatus')};
$('request').onclick=async()=>{try{const s=getSession();const d=await api('/rides/request',{method:'POST',body:JSON.stringify({customer_name:s.name,customer_phone:s.phone,origin:$('origin').value,destination:$('destination').value,origin_lat:customerOriginCoords?.lat||null,origin_lng:customerOriginCoords?.lng||null,destination_lat:customerDestinationCoords?.lat||null,destination_lng:customerDestinationCoords?.lng||null})});const holder=$('rideResult');holder.dataset.id=d.ride_id;result('rideResult',`Solicitud creada.<br><b>ID:</b> ${d.ride_id}<br><b>Tiempo estimado:</b> ${d.eta_minutes} min · <b>Precio:</b> ${d.estimated_price.toFixed(2)} €<br><small>Tarifa calculada desde ${d.fare_reference||'Entrevías'}</small>`);if(navigator.geolocation)startGps(customerMap,'customer',()=>s.phone,'customerGpsStatus',()=>d.ride_id)}catch(e){result('rideResult',e.message,true)}};
async function loadStops(){try{const stops=await api('/stops');const previous=$('driverStopId').value;$('driverStopId').innerHTML='<option value="">Selecciona una parada</option>'+stops.map(s=>`<option value="${s.id}">${s.name} · ${s.address||''}</option>`).join('');if(previous)$('driverStopId').value=previous;$('driverStops').innerHTML=stops.length?stops.map(s=>`<button class="stop-item" data-stop="${s.id}"><b>${s.name}</b><span>${s.address||'Sin dirección'}</span><small id="stopQueue-${s.id}">Cargando cola…</small></button>`).join(''):'<p>No hay paradas creadas.</p>';stops.forEach(async s=>{try{const q=await api('/queue/'+s.id);const el=$('stopQueue-'+s.id);if(el)el.textContent=q.length?`${q.length} taxistas · primero: ${q[0].name}`:'Sin taxistas en cola'}catch{}});document.querySelectorAll('.stop-item').forEach(b=>b.onclick=()=>selectStop(b.dataset.stop,stops));}catch(e){$('driverStopId').innerHTML='<option value="">No se pudieron cargar las paradas</option>';$('driverStops').textContent=e.message}}
function selectStop(id,stops){const s=stops.find(x=>x.id===id);if(!s)return;$('driverStopId').value=id;$('selectedStopName').textContent=s.name;$('stopDrawer').classList.add('hidden');if(s.latitude!==null&&s.longitude!==null){driverMap.setView([s.latitude,s.longitude],16)}}
$('driverStopId').onchange=()=>{const o=$('driverStopId').options[$('driverStopId').selectedIndex];$('selectedStopName').textContent=o?.value?o.text.split(' · ')[0]:'Ninguna'};
$('stopDrawerToggle').onclick=()=>$('stopDrawer').classList.toggle('hidden');$('closeStopDrawer').onclick=()=>$('stopDrawer').classList.add('hidden');
let driverWatching=false;
$('availabilityToggle').onclick=async()=>{const s=getSession();s.available=!s.available;saveSession(s);$('availabilityToggle').classList.toggle('on',s.available);$('availabilityToggle').innerHTML=s.available?'<i></i> Estado: Libre':'<i></i> Estado: Ocupado';try{const d=await api('/drivers/'+s.driverId+'/availability',{method:'POST',body:JSON.stringify({available:s.available})});if(!s.available){$('driverQueueCard')?.classList.add('hidden');$('driverGpsStatus').textContent='Ocupado · fuera de la cola'}else{$('driverGpsStatus').textContent='Libre · esperando GPS';if(!driverWatching){$('driverGps').click()}}}catch(e){s.available=!s.available;saveSession(s);$('availabilityToggle').classList.toggle('on',s.available);$('availabilityToggle').innerHTML=s.available?'<i></i> Estado: Libre':'<i></i> Estado: Ocupado';$('driverGpsStatus').textContent='No se pudo cambiar el estado'}};
function showQueueCard(stopId,position){const select=$('driverStopId');if([...select.options].some(o=>o.value===stopId)){select.value=stopId;$('selectedStopName').textContent=select.options[select.selectedIndex].text.split(' · ')[0]}const name=select.options[select.selectedIndex]?.text||'Parada seleccionada';$('driverQueueCard').classList.remove('hidden');$('queuePosition').textContent=position;$('queueTitle').textContent=`Turno ${position} en la parada unificada`;$('queueStop').textContent=name;$('queueTime').textContent=`Entrada registrada: ${new Date().toLocaleTimeString('es-ES')}`}
const rideLabels={accepted:'Servicio aceptado · preparado para ir a recoger',to_pickup:'Ir a recoger al cliente',picked_up:'Cliente recogido · rumbo al destino',completed:'Servicio terminado'};
function rideCard(r,active=false){let action='';if(r.status==='requested')action='<button class="service-action" data-ride-action="accept" data-ride="'+r.id+'">Aceptar servicio</button>';else if(r.status==='accepted')action='<button class="service-action" data-ride-action="to_pickup" data-ride="'+r.id+'">Ir a recoger</button>';else if(r.status==='to_pickup')action='<button class="service-action" data-ride-action="picked_up" data-ride="'+r.id+'">Cliente recogido</button>';else if(r.status==='picked_up')action='<button class="service-action" data-ride-action="completed" data-ride="'+r.id+'">Finalizar servicio</button>';return `<article class="service-card ${active?'service-active':''}"><div class="service-card-head"><b>${r.status==='requested'?'Nueva solicitud':(rideLabels[r.status]||'Servicio')}</b><small>${r.eta_minutes||'-'} min · ${(r.estimated_price||0).toFixed(2)} €</small></div><p><strong>Recogida:</strong> ${r.origin}</p><p><strong>Destino:</strong> ${r.destination||'Sin destino indicado'}</p>${r.customer_name?`<small>Cliente: ${r.customer_name}</small>`:''}${action}</article>`}
async function loadDriverRides(){const s=getSession();if(!s?.driverId||!$('driverRides'))return;try{const [open,own]=await Promise.all([s.available?api('/rides/open?driver_id='+encodeURIComponent(s.driverId)):Promise.resolve([]),api('/rides/driver/'+s.driverId)]);const active=own[0];let html='';if(active)html+=rideCard(active,true);if(s.available&&open.length)html+=open.filter(r=>r.id!==active?.id).map(r=>rideCard(r)).join('');$('driverRides').innerHTML=html||'<p>No hay servicios disponibles.</p>';$('driverRideStatus').textContent=active?'Servicio activo':(open.length&&s.available?`${open.length} solicitud(es) nuevas`:'Esperando solicitudes');document.querySelectorAll('[data-ride-action]').forEach(b=>b.onclick=()=>handleRideAction(b.dataset.ride,b.dataset.rideAction))}catch(e){$('driverRides').innerHTML='<p>No se pudieron actualizar los servicios.</p>'}}
async function handleRideAction(rideId,action){const s=getSession();try{if(action==='accept'){await api('/rides/'+rideId+'/accept',{method:'POST',body:JSON.stringify({driver_id:s.driverId})});s.available=false;s.activeRideId=rideId;saveSession(s);$('availabilityToggle').classList.remove('on');$('availabilityToggle').innerHTML='<i></i> Estado: Ocupado';$('driverGpsStatus').textContent='Servicio activo · fuera de la cola';$('driverQueueCard')?.classList.add('hidden')}else{const r=await api('/rides/'+rideId+'/status',{method:'POST',body:JSON.stringify({status:action})});if(action==='completed'){delete s.activeRideId;saveSession(s);$('driverGpsStatus').textContent='Servicio terminado · marca Estado: Libre para volver a la cola'}}loadDriverRides()}catch(e){$('driverRideStatus').textContent=e.message}}
let editingStopId=null;
async function loadAdminDashboard(){try{const [summary,stops,queue]=await Promise.all([api('/admin/summary'),api('/stops'),api('/queue')]);const stopById=Object.fromEntries(stops.map(s=>[s.id,s]));$('adminStops').innerHTML=stops.length?stops.map(s=>`<div class="admin-stop"><div><b>${s.name}</b><span>${s.address||'Sin dirección'} · ${s.latitude!==null&&s.longitude!==null?s.latitude.toFixed(5)+', '+s.longitude.toFixed(5):'sin coordenadas'}</span></div><button class="admin-mini" onclick="editStop('${s.id}')">Editar</button></div>`).join(''):'<p>No hay paradas creadas todavía.</p>';$('adminQueues').innerHTML=queue.length?queue.map(q=>`<div class="admin-queue"><div><b>${q.position}. ${q.name}</b><span>${stopById[q.stop_id]?.name||'Parada'} · entrada ${new Date(q.joined_at).toLocaleTimeString('es-ES')}</span></div><strong>${q.position}</strong><small>cola unificada</small></div>`).join(''):'<p>No hay taxistas en la cola unificada.</p>';$('adminDrivers').innerHTML=`<div class="admin-driver-summary"><b>${summary.active_drivers}</b><span>taxistas activos</span><b>${summary.today_rides}</b><span>servicios hoy</span></div>`}catch(e){$('adminQueues').textContent='No se pudo cargar la cola unificada.';$('adminDrivers').textContent=e.message}}
window.editStop=async id=>{const stops=await api('/stops'),s=stops.find(x=>x.id===id);if(!s)return;editingStopId=id;$('stopName').value=s.name;$('stopAddress').value=s.address||'';$('stopLat').value=s.latitude??'';$('stopLng').value=s.longitude??'';$('stopEntryRadius').value=s.radius_m||50;$('createStop').textContent='Guardar cambios';if(s.latitude&&s.longitude){adminMap.setView([s.latitude,s.longitude],16);if(adminMarker)adminMarker.setLatLng([s.latitude,s.longitude]);else adminMarker=L.marker([s.latitude,s.longitude]).addTo(adminMap)}}
$('createStop').onclick=async()=>{try{const payload={name:$('stopName').value,address:$('stopAddress').value,latitude:$('stopLat').value?Number($('stopLat').value):null,longitude:$('stopLng').value?Number($('stopLng').value):null,radius_m:Number($('stopEntryRadius').value)||50};if(payload.latitude===null||payload.longitude===null)return result('stopResult','Pulsa primero en el mapa para fijar la posición exacta.',true);const d=await api(editingStopId?('/stops/'+editingStopId):'/stops',{method:editingStopId?'PUT':'POST',body:JSON.stringify(payload)});result('stopResult',editingStopId?'Cambios guardados.':'Parada creada y guardada.');editingStopId=null;$('createStop').textContent='Crear parada';loadAdminDashboard()}catch(e){result('stopResult',e.message,true)}};
$('refresh').onclick=loadAdminDashboard;
$('saveFare').onclick=()=>{localStorage.setItem('taxiYaFare',JSON.stringify({flag:$('fareFlag').value,km:$('fareKm').value,minute:$('fareMinute').value,minimum:$('fareMinimum').value}));result('fareResult','Tarifa guardada en este dispositivo para la prueba.')}
api('/health').then(()=>$('notice').textContent='Servidor conectado · sesión protegida por perfil').catch(()=>$('notice').textContent='Servidor no disponible');
const session=getSession();if(session?.role==='customer')openCustomer(session);else if(session?.role==='driver')openDriver(session);else if(session?.role==='admin')openAdmin();else showAuth();
