const $=id=>document.getElementById(id), api=(path,opts={})=>fetch('/api'+path,{headers:{'Content-Type':'application/json'},...opts}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.detail||'Ha ocurrido un error');return d});
function result(id,msg,error=false){const e=$(id);e.className='result';if(error)e.classList.add('error');e.innerHTML=msg}
[...document.querySelectorAll('.tab')].forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.view).classList.add('active')});
api('/health').then(()=>$('notice').textContent='Servidor conectado · datos reales de prueba').catch(()=>$('notice').textContent='Servidor no disponible');
$('request').onclick=async()=>{try{const d=await api('/rides/request',{method:'POST',body:JSON.stringify({customer_name:$('customerName').value,customer_phone:$('customerPhone').value,origin:$('origin').value,destination:$('destination').value})});result('rideResult',`Solicitud creada.<br><b>ID:</b> ${d.ride_id}<br><b>Tiempo estimado:</b> ${d.eta_minutes} min · <b>Precio:</b> ${d.estimated_price.toFixed(2)} €`)}catch(e){result('rideResult',e.message,true)}};
$('register').onclick=async()=>{try{const d=await api('/drivers/register',{method:'POST',body:JSON.stringify({name:$('driverName').value,phone:$('driverPhone').value,license:$('license').value,plate:$('plate').value})});$('driverId').value=d.driver_id;result('driverResult',`Registro creado.<br><b>ID:</b> ${d.driver_id}<br>Ahora introduce la clave y pulsa Activar.`)}catch(e){result('driverResult',e.message,true)}};
$('activate').onclick=async()=>{try{const d=await api('/drivers/activate',{method:'POST',body:JSON.stringify({driver_id:$('driverId').value,code:$('code').value,device_id:'web-demo-'+Date.now()})});result('queueResult',`Cuenta activada y móvil vinculado. Estado: <b>${d.status}</b>`)}catch(e){result('queueResult',e.message,true)}};
$('createStop').onclick=async()=>{try{const d=await api('/stops',{method:'POST',body:JSON.stringify({name:$('stopName').value,address:$('stopAddress').value})});$('stopId').value=d.id;result('stopResult',`Parada creada.<br><b>ID:</b> ${d.id}<br>Puedes usar este ID en la pestaña Taxista.`)}catch(e){result('stopResult',e.message,true)}};
$('join').onclick=async()=>{try{const d=await api('/queue/join',{method:'POST',body:JSON.stringify({stop_id:$('stopId').value,driver_id:$('driverId').value})});result('queueResult',`Has entrado en la cola.<br><b>Posición:</b> ${d.position}`)}catch(e){result('queueResult',e.message,true)}};
$('refresh').onclick=async()=>{try{const d=await api('/admin/summary');$('summary').innerHTML=`<div><b>${d.stops}</b><span>Paradas activas</span></div><div><b>${d.active_drivers}</b><span>Taxistas activos</span></div><div><b>${d.today_rides}</b><span>Servicios hoy</span></div>`}catch(e){$('summary').textContent=e.message}};$('refresh').click();
