const $=id=>document.getElementById(id);
const SESSION_KEY='taxiYaSession';
const api=(path,opts={})=>fetch('/api'+path,{headers:{'Content-Type':'application/json',...(opts.headers||{})},...opts}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.detail||'Ha ocurrido un error');return d});
function result(id,msg,error=false){const e=$(id);e.className='result';if(error)e.classList.add('error');e.innerHTML=msg}
function hideAll(){document.querySelectorAll('#auth .onboarding,#rolePicker,.role-view').forEach(e=>e.classList.add('hidden'))}
function saveSession(s){localStorage.setItem(SESSION_KEY,JSON.stringify(s))}
function getSession(){try{return JSON.parse(localStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
function showAuth(){localStorage.removeItem(SESSION_KEY);watchers.forEach(w=>navigator.geolocation.clearWatch(w));watchers.length=0;hideAll();$('auth').classList.remove('hidden');$('rolePicker').classList.remove('hidden')}
function showOnboarding(id){hideAll();$('auth').classList.remove('hidden');$(id).classList.remove('hidden')}
function openCustomer(s){hideAll();$('auth').classList.add('hidden');$('customerApp').classList.remove('hidden');$('customerWelcome').textContent=` · ${s.name}`;$('customerNameHidden')?.remove();ensureCustomerMap()}
function openDriver(s){hideAll();$('auth').classList.add('hidden');$('driverApp').classList.remove('hidden');$('driverWelcome').textContent=` · ${s.name}`;$('availabilityToggle').classList.toggle('on',!!s.available);$('availabilityToggle').innerHTML=s.available?'<i></i> En servicio':'<i></i> Estoy disponible';ensureDriverMap();loadStops()}
function openAdmin(){hideAll();$('auth').classList.add('hidden');$('adminApp').classList.remove('hidden');ensureAdminMap();loadAdminDashboard()}

document.querySelectorAll('[data-logout]').forEach(b=>b.onclick=showAuth);
$('chooseCustomer').onclick=()=>showOnboarding('customerOnboarding');
$('chooseDriver').onclick=()=>showOnboarding('driverOnboarding');
$('chooseAdmin').onclick=()=>showOnboarding('adminOnboarding');
$('customerEnter').onclick=()=>{const name=$('customerSignupName').value.trim(),phone=$('customerSignupPhone').value.trim();if(!name||!phone)return result('rideResult','Indica nombre y teléfono.',true);saveSession({role:'customer',name,phone});openCustomer({role:'customer',name,phone})};
$('adminEnter').onclick=()=>{if($('adminCode').value!=='123456'){result('adminLoginResult','Clave incorrecta.',true);return}saveSession({role:'admin'});openAdmin()};
$('register').onclick=async()=>{try{const d=await api('/drivers/register',{method:'POST',body:JSON.stringify({name:$('driverName').value,phone:$('driverPhone').value,license:$('license').value,plate:$('plate').value})});$('driverId').value=d.driver_id;$('driverActivation').classList.remove('hidden');result('driverResult','Registro creado. Ahora activa tu perfil con la clave.')}catch(e){result('driverResult',e.message,true)}};
$('activate').onclick=async()=>{try{const d=await api('/drivers/activate',{method:'POST',body:JSON.stringify({driver_id:$('driverId').value,code:$('code').value,device_id:'web-demo-'+Date.now()})});const s={role:'driver',driverId:$('driverId').value,name:$('driverName').value,phone:$('driverPhone').value,status:d.status};saveSession(s);openDriver(s)}catch(e){result('driverResult',e.message,true)}};

const alcantarilla=[37.969,-1.217];const maps=[];const markers={};let customerMap,driverMap,adminMap;const watchers=[];
function makeMap(id){const map=L.map(id,{preferCanvas:true}).setView(alcantarilla,14);L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'© Esri, © OpenStreetMap'}).addTo(map);L.marker(alcantarilla).addTo(map).bindPopup('Alcantarilla · Taxi Ya');maps.push(map);map.whenReady(()=>{map.invalidateSize();setTimeout(()=>map.invalidateSize(),500)});return map}
function ensureCustomerMap(){if(!customerMap)customerMap=makeMap('customerMap');setTimeout(()=>customerMap.invalidateSize(),100)}
function ensureDriverMap(){if(!driverMap)driverMap=makeMap('driverMap');setTimeout(()=>driverMap.invalidateSize(),100)}
let adminMarker;
function ensureAdminMap(){if(!adminMap){adminMap=makeMap('adminMap');adminMap.on('click',e=>{const lat=e.latlng.lat.toFixed(6),lng=e.latlng.lng.toFixed(6);$('stopLat').value=lat;$('stopLng').value=lng;if(adminMarker)adminMarker.setLatLng(e.latlng);else adminMarker=L.marker(e.latlng).addTo(adminMap).bindPopup('Nueva parada').openPopup()})}setTimeout(()=>adminMap.invalidateSize(),100)}
setTimeout(()=>maps.forEach(m=>m.invalidateSize()),1200);window.addEventListener('resize',()=>maps.forEach(m=>m.invalidateSize()));
function startGps(map,role,idProvider,statusId,rideProvider){if(!navigator.geolocation){$(statusId).textContent='GPS no disponible';return}$(statusId).textContent='Solicitando permiso…';const w=navigator.geolocation.watchPosition(async pos=>{const lat=pos.coords.latitude,lng=pos.coords.longitude;map.setView([lat,lng],16);if(markers[role])markers[role].setLatLng([lat,lng]);else markers[role]=L.marker([lat,lng]).addTo(map).bindPopup(role==='driver'?'Ubicación del taxi':'Tu ubicación');$(statusId).textContent='Ubicación compartida';try{const sync=await api('/locations',{method:'POST',body:JSON.stringify({entity_id:idProvider(),role,lat,lng,ride_id:rideProvider?rideProvider():null})});if(role==='driver'&&sync.auto_queue){showQueueCard(sync.auto_queue.stop_id,sync.auto_queue.position);$(statusId).textContent=`En cola · ${sync.auto_queue.stop_name}`}else if(role==='driver'&&sync.exited_stop_ids?.length){$('driverQueueCard')?.classList.add('hidden');$(statusId).textContent='Fuera de la parada'}}catch(e){$(statusId).textContent='GPS activo · sincronización pendiente'}},()=>$(statusId).textContent='Permiso de ubicación no concedido',{enableHighAccuracy:true,maximumAge:10000,timeout:15000});watchers.push(w)}
$('customerGps').onclick=()=>{const s=getSession();startGps(customerMap,'customer',()=>s.phone,'customerGpsStatus',()=>$('rideResult')?.dataset.id||null)};
$('driverGps').onclick=()=>{if(driverWatching)return;const s=getSession();driverWatching=true;startGps(driverMap,'driver',()=>s.driverId,'driverGpsStatus')};
$('request').onclick=async()=>{try{const s=getSession();const d=await api('/rides/request',{method:'POST',body:JSON.stringify({customer_name:s.name,customer_phone:s.phone,origin:$('origin').value,destination:$('destination').value})});const holder=$('rideResult');holder.dataset.id=d.ride_id;result('rideResult',`Solicitud creada.<br><b>ID:</b> ${d.ride_id}<br><b>Tiempo estimado:</b> ${d.eta_minutes} min · <b>Precio:</b> ${d.estimated_price.toFixed(2)} €`);if(navigator.geolocation)startGps(customerMap,'customer',()=>s.phone,'customerGpsStatus',()=>d.ride_id)}catch(e){result('rideResult',e.message,true)}};
async function loadStops(){try{const stops=await api('/stops');const previous=$('driverStopId').value;$('driverStopId').innerHTML='<option value="">Selecciona una parada</option>'+stops.map(s=>`<option value="${s.id}">${s.name} · ${s.address||''}</option>`).join('');if(previous)$('driverStopId').value=previous;$('driverStops').innerHTML=stops.length?stops.map(s=>`<button class="stop-item" data-stop="${s.id}"><b>${s.name}</b><span>${s.address||'Sin dirección'}</span><small id="stopQueue-${s.id}">Cargando cola…</small></button>`).join(''):'<p>No hay paradas creadas.</p>';stops.forEach(async s=>{try{const q=await api('/queue/'+s.id);const el=$('stopQueue-'+s.id);if(el)el.textContent=q.length?`${q.length} taxistas · primero: ${q[0].name}`:'Sin taxistas en cola'}catch{}});document.querySelectorAll('.stop-item').forEach(b=>b.onclick=()=>selectStop(b.dataset.stop,stops));}catch(e){$('driverStopId').innerHTML='<option value="">No se pudieron cargar las paradas</option>';$('driverStops').textContent=e.message}}
function selectStop(id,stops){const s=stops.find(x=>x.id===id);if(!s)return;$('driverStopId').value=id;$('selectedStopName').textContent=s.name;$('stopDrawer').classList.add('hidden');if(s.latitude!==null&&s.longitude!==null){driverMap.setView([s.latitude,s.longitude],16)}}
$('driverStopId').onchange=()=>{const o=$('driverStopId').options[$('driverStopId').selectedIndex];$('selectedStopName').textContent=o?.value?o.text.split(' · ')[0]:'Ninguna'};
$('stopDrawerToggle').onclick=()=>$('stopDrawer').classList.toggle('hidden');$('closeStopDrawer').onclick=()=>$('stopDrawer').classList.add('hidden');
let driverWatching=false;
$('availabilityToggle').onclick=()=>{const s=getSession();s.available=!s.available;saveSession(s);$('availabilityToggle').classList.toggle('on',s.available);$('availabilityToggle').innerHTML=s.available?'<i></i> En servicio':'<i></i> Estoy disponible';if(s.available&&!driverWatching){driverWatching=true;$('driverGps').click()}if(!s.available)$('driverGpsStatus').textContent='GPS pausado'};
function showQueueCard(stopId,position){const select=$('driverStopId');if([...select.options].some(o=>o.value===stopId)){select.value=stopId;$('selectedStopName').textContent=select.options[select.selectedIndex].text.split(' · ')[0]}const name=select.options[select.selectedIndex]?.text||'Parada seleccionada';$('driverQueueCard').classList.remove('hidden');$('queuePosition').textContent=position;$('queueTitle').textContent=`Turno ${position} en la parada unificada`;$('queueStop').textContent=name;$('queueTime').textContent=`Entrada registrada: ${new Date().toLocaleTimeString('es-ES')}`}
$('join').onclick=async()=>{try{const s=getSession(),stop=$('driverStopId').value;if(!stop)return result('queueResult','Selecciona una parada.',true);const d=await api('/queue/join',{method:'POST',body:JSON.stringify({stop_id:stop,driver_id:s.driverId})});showQueueCard(stop,d.position);result('queueResult','Estás dentro de la cola unificada.')}catch(e){result('queueResult',e.message,true)}};
let editingStopId=null;
async function loadAdminDashboard(){try{const [summary,stops]=await Promise.all([api('/admin/summary'),api('/stops')]);const queues=await Promise.all(stops.map(async s=>({stop:s,queue:await api('/queue/'+s.id)})));$('adminStops').innerHTML=stops.length?stops.map(s=>`<div class="admin-stop"><div><b>${s.name}</b><span>${s.address||'Sin dirección'} · ${s.latitude!==null&&s.longitude!==null?s.latitude.toFixed(5)+', '+s.longitude.toFixed(5):'sin coordenadas'}</span></div><button class="admin-mini" onclick="editStop('${s.id}')">Editar</button></div>`).join(''):'<p>No hay paradas creadas todavía.</p>';$('adminQueues').innerHTML=queues.length?queues.map(({stop,queue})=>`<div class="admin-queue"><div><b>${stop.name}</b><span>${stop.address||''}</span></div><strong>${queue.length}</strong><small>${queue.length===1?'taxista en cola':'taxistas en cola'}</small></div>`).join(''):'<p>No hay paradas creadas todavía.</p>';$('adminDrivers').innerHTML=`<div class="admin-driver-summary"><b>${summary.active_drivers}</b><span>taxistas activos</span><b>${summary.today_rides}</b><span>servicios hoy</span></div>`}catch(e){$('adminQueues').textContent='No se pudieron cargar las colas.';$('adminDrivers').textContent=e.message}}
window.editStop=async id=>{const stops=await api('/stops'),s=stops.find(x=>x.id===id);if(!s)return;editingStopId=id;$('stopName').value=s.name;$('stopAddress').value=s.address||'';$('stopLat').value=s.latitude??'';$('stopLng').value=s.longitude??'';$('stopEntryRadius').value=s.radius_m||50;$('createStop').textContent='Guardar cambios';if(s.latitude&&s.longitude){adminMap.setView([s.latitude,s.longitude],16);if(adminMarker)adminMarker.setLatLng([s.latitude,s.longitude]);else adminMarker=L.marker([s.latitude,s.longitude]).addTo(adminMap)}}
$('createStop').onclick=async()=>{try{const payload={name:$('stopName').value,address:$('stopAddress').value,latitude:$('stopLat').value?Number($('stopLat').value):null,longitude:$('stopLng').value?Number($('stopLng').value):null,radius_m:Number($('stopEntryRadius').value)||50};if(payload.latitude===null||payload.longitude===null)return result('stopResult','Pulsa primero en el mapa para fijar la posición exacta.',true);const d=await api(editingStopId?('/stops/'+editingStopId):'/stops',{method:editingStopId?'PUT':'POST',body:JSON.stringify(payload)});result('stopResult',editingStopId?'Cambios guardados.':'Parada creada y guardada.');editingStopId=null;$('createStop').textContent='Crear parada';loadAdminDashboard()}catch(e){result('stopResult',e.message,true)}};
$('refresh').onclick=loadAdminDashboard;
$('saveFare').onclick=()=>{localStorage.setItem('taxiYaFare',JSON.stringify({flag:$('fareFlag').value,km:$('fareKm').value,minute:$('fareMinute').value,minimum:$('fareMinimum').value}));result('fareResult','Tarifa guardada en este dispositivo para la prueba.')}
api('/health').then(()=>$('notice').textContent='Servidor conectado · sesión protegida por perfil').catch(()=>$('notice').textContent='Servidor no disponible');
const session=getSession();if(session?.role==='customer')openCustomer(session);else if(session?.role==='driver')openDriver(session);else if(session?.role==='admin')openAdmin();else showAuth();
